== Contributing

When contributing to this repository, please first discuss the change
you wish to make via issue, email, or any other method with the owners
of this repository before making a change.

Please note we have a code of conduct, please follow it in all your
interactions with the project.

=== Pull Request Process

[arabic]
. Ensure any install or build dependencies are removed before the end of
the layer when doing a build.
. Use meaningful commit messages. Stick to the format based on
https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].
. Update the `CHANGELOG.md` file with details of the changes you made.
Stick to the format based on https://keepachangelog.com/en/1.0.0/[Keep a
Changelog].
. Update the `README.md` file if it is necessary. Keep in mind that most
of the times only excessive changes will require changes in this file.
. Increase the version numbers in any examples to the new version that
this Pull Request would represent. The versioning scheme we use is
https://semver.org/spec/v2.0.0.html[Semantic Versioning].
. You may merge the Pull Request in once you have the sign-off of at
least one other leading developer, or if you do not have permission to
do that, you may request the reviewer to merge it for you.
